# Data paths
paths:
  raw_dir: "data/raw"
  transformed_dir: "data/transformed"
  census_input: "data/transformed/admin_boundaries_ORP.geojson"
  census_output: "data/transformed/admin_boundaries_ORP_variables.geojson"
  clustered_output: "data/processed/clusters.geojson"
  processed_dir: "data/visualizations" # Folder for the PNG

# Projection Settings
projection:
  target_epsg: 5514

# Clustering Parameters
clustering:
  n_clusters: 5
  random_state: 42

  features:
    - 'POP_DENS' 
    - 'PCT_WOMEN'
    - 'PCT_CHILD'
    - 'PCT_WORKING'
    - 'PCT_ELDERLY'
    - 'AGEING_INDEX'
    - 'DEPENDENCY'
    - 'NATURAL_INC_RATE'
    - 'MIG_BAL_RATE'

visualization:
  output_filename: "cluster_map.png"
  cmap: "tab10" 
  title: "ORP Clusters based on 9 Selected Variables"

# Valhalla Settings
#valhalla:
#  url: "http://localhost:8002"
#  costing: "auto"