# Data paths
#paths:
#  census_raw: "data/raw/census_data.csv" PLACEHOLDER
#  boundaries: "data/raw/districts.geojson"
#  hospitals: "data/raw/hospital.geojson"
#  maternity: "data/raw/maternity_points.geojson"
#  output_final: "data/final/results.csv" ?????????????

# Clustering Parameters
clustering:
  n_clusters: 5
  random_state: 42

  features:
    - Z_POP_DENS
    - Z_PCT_WOMEN
    - Z_PCT_CHILD
    - Z_PCT_ELDERLY
    - Z_AGEING_INDEX
    - Z_DEPENDENCY
    - Z_MIRA_NEZAM #unemployment rate
    - Z_NATURAL_INC_RATE
    - Z_MIG_BAL_RATE

# Valhalla Settings
#valhalla:
#  url: "http://localhost:8002"
#  costing: "auto"